---------------------------------------------------------------
----------------------REGISTER OTHER COMPLAINT-----------------
---------------------------------------------------------------
BEGIN (INSRT010_COMPLAINT)
	INSERT INTO 
	COMPLAINT (
	PHONE_NUMBER_ONE, 
	SERVICE_ID, 
	UNIT_ID, 
	CALL_RATE_ID, 
	CALLER_EMAIL, 
	CALLER_NAME, 
	DETAILED_SERVICE_ID, 
    CALL_SORT_ID, 
	CALL_RESULT_ID, 
	SOURCE_ID,
	COMPLAINT_COMMENT,
	SOLVED_STATUS,
	AGENT_ID,
	INSERT_USER,
	INSERT_DATE) 
	VALUES (
	:PHONE_NUMBER_ONE, 
	:SERVICE_ID, 
	:UNIT_ID, 
	:CALL_RATE_ID, 
	:CALLER_EMAIL, 
	:CALLER_NAME, 
	:DETAILED_SERVICE_ID, 
	:CALL_SORT_ID, 
	:CALL_RESULT_ID, 
	:SOURCE_ID,
	:COMPLAINT_COMMENT,
	:SOLVED_STATUS,
	:AGENT_ID,
	:INSERT_USER,
	TO_TIMESTAMP(:INSERT_DATE,'YYYY-MM-DD:HH24:MI:SS'))
END
---------------------------------------------------------------
--------------COMPLAINT HISTORY/COMPLAINT REGISTER-------------
---------------------------------------------------------------
BEGIN(SEARCH_COMPLAINT_HISTORY_PS_301)
	SELECT
	C.COMPLAINT_LIST_ID AS COMPLAINT_LIST_ID
	,C.PHONE_NUMBER_ONE AS PHONE_NUMBER
	,C.AGENT_ID || ' ' || A.FIRSTNAME || ' ' || A.LASTNAME AS AGENT_NAME
	,S1.SERVICE_NAME AS SERVICE_NAME
	,S2.SERVICE_NAME AS DETAILED_SERVICE_NAME
	,CRA.CALL_RATE_NAME AS CALL_RATE
	,TO_CHAR(C.SOLVED_DATE,'YYYY-MM-DD') AS SOLVED_DATE
	,U.UNIT_NAME AS UNIT_NAME
	,CRE.CALL_RESULT_NAME AS CALL_RESULT
  	,C.CALLER_NAME AS CALLER_NAME
  	,C.CALLER_EMAIL AS CALLER_EMAIL
  	,C.COMPLAINT_COMMENT AS COMPLAINT_COMMENT
  	,C.EXPENSE AS EXPENSE
  	,C.CALL_RESULT_ID AS CALL_RESULT_ID
  	,C.CALL_SORT_ID AS CALL_SORT_ID
  	,C.SOLVED_COMMENT AS SOLVED_COMMENT
  	,MS.SOURCE_NAME AS SOURCE_NAME
	FROM COMPLAINT C
	LEFT JOIN MST_SOURCE MS
	ON MS.SOURCE_ID=C.SOURCE_ID
	LEFT JOIN MST_AGENT A
	ON A.AGENT_ID=C.AGENT_ID
	LEFT JOIN MST_SERVICE S1
	ON S1.SERVICE_ID=C.SERVICE_ID AND S1.CALL_REQ_TYPE_ID='4'
	LEFT JOIN MST_SERVICE S2
	ON S2.SERVICE_ID=C.DETAILED_SERVICE_ID AND S2.CALL_REQ_TYPE_ID='4'
	LEFT JOIN MST_CALL_RATE CRA
	ON CRA.CALL_RATE_ID=C.CALL_RATE_ID
	LEFT JOIN MST_CALL_RESULT CRE
	ON CRE.CALL_RESULT_ID=C.CALL_RESULT_ID
	LEFT JOIN MST_UNIT U
	ON U.UNIT_ID=C.UNIT_ID
	WHERE :WHERE
	AND C.SOLVED_STATUS='1'
	AND C.DELETE_USER IS NULL
	:ORDER
END
---------------------------------------------------------------
BEGIN(SEARCH_COMPLAINT_HISTORY_CNT_PS_301)
	SELECT
		count(*) as CNT
	FROM
		COMPLAINT C
	LEFT JOIN MST_SERVICE S1
	ON S1.SERVICE_ID=C.SERVICE_ID AND S1.CALL_REQ_TYPE_ID='4'
	LEFT JOIN MST_SERVICE S2
	ON S2.SERVICE_ID=C.DETAILED_SERVICE_ID AND S2.CALL_REQ_TYPE_ID='4'
	WHERE :WHERE 
	AND C.DELETE_USER IS NULL
	AND C.SOLVED_STATUS='1'
END
---------------------------------------------------------------
BEGIN(SEARCH_COMPLAINT_PS_301)
	SELECT 
	C.COMPLAINT_LIST_ID AS COMPLAINT_LIST_ID
	,C.PHONE_NUMBER_ONE AS PHONE_NUMBER
	,C.AGENT_ID || ' ' || A.FIRSTNAME || ' ' || A.LASTNAME AS AGENT_NAME
	,C.AGENT_ID AS AGENT_ID
	,S1.SERVICE_NAME AS SERVICE_NAME
	,S2.SERVICE_NAME AS DETAILED_SERVICE_NAME
	,CR.CALL_RATE_NAME AS CALL_RATE
	,CS.CALL_SORT_NAME AS CALL_SORT
	,TO_CHAR(C.DEADLINE, 'YYYY-MM-DD') AS DEADLINE
  	,C.CALLER_EMAIL AS CALLER_EMAIL
  	,C.CALLER_NAME AS CALLER_NAME
  	,C.COMPLAINT_COMMENT AS COMPLAINT_COMMENT
  	,TO_CHAR(C.SOLVED_DATE,'YYYY-MM-DD') AS SOLVED_DATE
  	,C.EXPENSE AS EXPENSE
  	,C.CALL_RESULT_ID AS CALL_RESULT_ID
  	,C.CALL_SORT_ID AS CALL_SORT_ID
  	,C.SOLVED_COMMENT AS SOLVED_COMMENT
  	,U.UNIT_NAME AS UNIT_NAME
  	,TO_CHAR(C.INSERT_DATE, 'YYYY-MM-DD') AS INSERT_DATE
  	,C.SOLVED_STATUS AS SOLVED_STATUS
  	,MS.SOURCE_NAME AS SOURCE_NAME
	FROM
	COMPLAINT C
	LEFT JOIN MST_SOURCE MS
 	ON MS.SOURCE_ID=C.SOURCE_ID
	LEFT JOIN MST_AGENT A
	ON A.AGENT_ID=C.AGENT_ID
	LEFT JOIN MST_SERVICE S1
	ON S1.SERVICE_ID=C.SERVICE_ID AND S1.CALL_REQ_TYPE_ID='4'
	LEFT JOIN MST_SERVICE S2
	ON S2.SERVICE_ID=C.DETAILED_SERVICE_ID AND S2.CALL_REQ_TYPE_ID='4'
	LEFT JOIN MST_CALL_RATE CR
	ON CR.CALL_RATE_ID=C.CALL_RATE_ID
	LEFT JOIN MST_CALL_SORT CS
	ON CS.CALL_SORT_ID=C.CALL_SORT_ID
  	LEFT JOIN MST_UNIT U
  	ON U.UNIT_ID=C.UNIT_ID
	WHERE 
	:WHERE
	AND (C.SOLVED_STATUS='0' OR C.SOLVED_STATUS='2')
	AND C.DELETE_USER IS NULL
	:ORDER
END
---------------------------------------------------------------
BEGIN(SEARCH_COMPLAINT_CNT_PS_301)
SELECT
		count(*) as CNT
	FROM
		COMPLAINT C
	LEFT JOIN MST_SERVICE S1
	ON S1.SERVICE_ID=C.SERVICE_ID AND S1.CALL_REQ_TYPE_ID='4'
	LEFT JOIN MST_SERVICE S2
	ON S2.SERVICE_ID=C.DETAILED_SERVICE_ID AND S2.CALL_REQ_TYPE_ID='4'
	WHERE 
	:WHERE 
	AND C.DELETE_USER IS NULL
	AND (C.SOLVED_STATUS='0' OR C.SOLVED_STATUS='2')
END
---------------------------------------------------------------
BEGIN(UPDT_COMPLAINT_DETAILS_PS_301)
	UPDATE COMPLAINT
	SET 
  	CALLER_EMAIL=:CALLER_EMAIL,
	CALL_RESULT_ID=:CALL_RESULT_ID,
	AGENT_ID=:AGENT_ID,
	SOLVED_DATE=TO_TIMESTAMP(:SOLVED_DATE,'YYYY-mm-DD HH24:MI:SS'),
	EXPENSE=:EXPENSE,
	CALL_SORT_ID=:CALL_SORT_ID,
	SOLVED_COMMENT=:SOLVED_COMMENT,
	UPDATE_USER=:UPDATE_USER,
	UPDATE_DATE=TO_TIMESTAMP(:UPDATE_DATE,'YYYY-MM-DD HH24:MI:SS')
	WHERE 
  	COMPLAINT_LIST_ID=:COMPLAINT_LIST_ID
END
--------------------------------------------------------------
BEGIN(SLCT_COMPLAINT_DETAILS_PS_301)
	SELECT 
    C.CALLER_NAME AS CALLER_NAME,
    C.CALLER_EMAIL AS CALLER_EMAIL,
    C.COMPLAINT_COMMENT AS COMPLAINT_COMMENT,
    C.SOLVED_DATE AS SOLVED_DATE,
    C.EXPENSE AS EXPENSE,
    C.CALL_RESULT_ID AS CALL_RESULT_ID,
    C.CALL_SORT_ID AS CALL_SORT_ID,
    C.SOLVED_COMMENT AS SOLVED_COMMENT,
    C.COMPLAINT_COMMENT AS COMPLAINT_COMMENT,
    C.UNIT_ID || ' ' || U.UNIT_NAME AS UNIT_NAME
    FROM
    COMPLAINT C
    LEFT JOIN MST_UNIT U
    ON U.UNIT_ID=C.UNIT_ID
    WHERE C.DELETE_USER IS NULL
    AND C.COMPLAINT_LIST_ID=:COMPLAINT_LIST_ID
END
--------------------------------------------------------------
BEGIN(SLCT_COMPLAINT_HISTORY_DETAILS_PS_301)
	SELECT 
	C.CALLER_NAME AS CALLER_NAME,
    C.CALLER_EMAIL AS CALLER_EMAIL,
    C.COMPLAINT_COMMENT AS COMPLAINT_COMMENT,
    C.SOLVED_DATE AS SOLVED_DATE,
    C.EXPENSE AS EXPENSE,
    C.CALL_RESULT_ID AS CALL_RESULT_ID,
    C.CALL_SORT_ID AS CALL_SORT_ID,
    C.SOLVED_COMMENT AS SOLVED_COMMENT,
    C.COMPLAINT_COMMENT AS COMPLAINT_COMMENT,
    C.UNIT_ID || ' ' || U.UNIT_NAME AS UNIT_NAME
    FROM
    COMPLAINT C
    LEFT JOIN MST_UNIT U
    ON U.UNIT_ID=C.UNIT_ID
    WHERE C.DELETE_USER IS NULL
    AND C.COMPLAINT_LIST_ID=:COMPLAINT_LIST_ID
END
---------------------------------------------------------------
BEGIN(SOLVE_COMPLAINT_PS_301)
	UPDATE COMPLAINT SET SOLVED_STATUS=:SOLVED_STATUS
	WHERE COMPLAINT_LIST_ID=:COMPLAINT_LIST_ID
END
---------------------------------------------------------------
BEGIN(CHECK_MIGRATION_PS_301)
	SELECT MIGRATION_NUM FROM MST_CALL_RESULT WHERE CALL_RESULT_ID=:CALL_RESULT_ID
END
---------------------------------------------------------------
BEGIN(DLT_COMPLAINT_PS_301)
	UPDATE COMPLAINT SET 
	DELETE_USER=:DELETE_USER,
	DELETE_DATE=TO_TIMESTAMP(:DELETE_DATE ,'YYYY-MM-DD HH24:MI:SS')
	WHERE COMPLAINT_LIST_ID=:COMPLAINT_LIST_ID
END
---------------------------------------------------------------
BEGIN(SEND_COMPLAINT_TO_TASK_PS_301)
	INSERT INTO TASK
	(CALL_HISTORY_ID,
	CALLTYPE,
	PHONE_NUMBER_ONE,
	CALLER_NAME,
	INSERT_AGENT,
	TASK_NAME,
	TASK_COMMENT,
	DEADLINE,
	AGENT_ID,
	CALL_REQ_TYPE_ID,
	ACTIVE_TASK
	)
	SELECT 
	C.CALL_HISTORY_ID,
	CH.CALLTYPE,
	C.PHONE_NUMBER_ONE,
	C.CALLER_NAME,
	C.AGENT_ID,
	CHS.CALL_NAME,
	C.COMPLAINT_COMMENT,
	CHS.DEADLINE,
	C.AGENT_ID,
	'4' AS CALL_REQ_TYPE_ID,
	'1' AS ACTIVE_TASK
	FROM
	COMPLAINT C
	LEFT JOIN CALL_HISTORY CH
	ON CH.CALL_HISTORY_ID=C.CALL_HISTORY_ID
	LEFT JOIN CALL_HISTORY_SERVICE CHS
	ON CHS.CALL_HISTORY_ID=C.CALL_HISTORY_ID
	WHERE COMPLAINT_LIST_ID=:COMPLAINT_LIST_ID
END
--------------------------------------------------------------
BEGIN(INSRT_TO_TASK_LIST_PS_301)
	INSERT INTO TASK
	(
	PHONE_NUMBER_ONE,
	CALLER_NAME,
	INSERT_AGENT,
	TASK_COMMENT,
	CALL_REQ_TYPE_ID
	)
	VALUES(
	:PHONE_NUMBER_ONE, 
	:CALLER_NAME, 
	:AGENT_ID,
	:COMPLAINT_COMMENT,
	'4'
	)
END
--------------------------------------------------------------
------------------------CALLERHISTORY-------------------------
--------------------------------------------------------------
BEGIN(GRID_CALLER_HISTORY)
	SELECT
	I.PHONE_NUMBER_ONE AS PHONE_NUMBER_ONE,
	I.PHONE_NUMBER_TWO AS PHONE_NUMBER_TWO,
	CQ.CALL_REQ_TYPE_NAME AS CALL_REQ_TYPE_NAME,
	CR.CALL_RESULT_NAME AS CALL_RESULT_NAME,
	I.START_TIME AS START_TIME,
	I.AGENT_ID AS AGENT_ID,
	I.CALLTYPE AS CALLTYPE,
	I.SEND_STATUS AS SEND_STATUS
	FROM INBOUND I
	LEFT JOIN MST_CALL_REQ_TYPE CQ
	ON CQ.CALL_REQ_TYPE_ID=I.CALL_REQ_TYPE_ID
	LEFT JOIN CALL_COMMENT IC
	ON IC.CALL_HISTORY_ID=I.CALL_HISTORY_ID
	LEFT JOIN MST_CALL_RESULT CR
	ON CR.CALL_RESULT_ID=IC.CALL_RESULT_ID
END



