----------------------------ComplaintReport-----------------------------------------------------------------------------------------
BEGIN(Complaint)
	select
		to_char(CH.START_TIME, 'YYYY-MM-DD') as F1,
		to_char(CH.START_TIME, 'DY') as F2,
		SUBSTR(AG.LASTNAME, 1,1) || '.' || AG.FIRSTNAME as F3,
		US.FIRSTNAME as F4,
		US.PHONENUMBER as F5,


		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = SERVICE_TYPE1 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F6_1,
		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = DETAILED_SERVICE_TYPE1 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F7_1,

		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = SERVICE_TYPE2 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F6_2,
		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = DETAILED_SERVICE_TYPE2 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F7_2,

		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = SERVICE_TYPE3 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F6_3,
		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = DETAILED_SERVICE_TYPE3 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F7_3,

		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = SERVICE_TYPE4 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F6_4,
		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = DETAILED_SERVICE_TYPE4 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F7_4,

		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = SERVICE_TYPE5 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F6_5,
		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = DETAILED_SERVICE_TYPE5 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F7_5,

		CALL_COMMENT as F8,
		(SELECT UNIT_NAME FROM MST_UNIT MU WHERE MU.UNIT_ID = CHS.UNIT_ID) as F9,
		(SELECT CALL_SORT_NAME FROM MST_CALL_SORT MCS WHERE MCS.CALL_SORT_ID = CHS.CALL_SORT_ID) as F10


	from CALL_HISTORY_SERVICE CHS

	LEFT JOIN CALL_HISTORY CH ON CH.CALL_HISTORY_ID = CHS.CALL_HISTORY_ID
	LEFT JOIN MST_AGENT AG ON AG.AGENT_ID = CH.AGENT_ID
	LEFT JOIN MST_USERS US ON US.PHONENUMBER = CH.PHONENUMBER

	where CALL_REQ_TYPE = 4 AND (:DATE_FROM IS NULL OR :DATE_FROM <= to_char(CH.START_TIME, 'YYYY-MM-DD')) AND (:DATE_TO IS NULL OR :DATE_TO >= to_char(CH.START_TIME, 'YYYY-MM-DD')) AND (:AGENT_ID IS NULL OR :AGENT_ID = CH.AGENT_ID)
END
----------------------------AppealReport-----------------------------------------------------------------------------------------
BEGIN(Appeal)
		select
		to_char(CH.START_TIME, 'YYYY-MM-DD') as F1,
		to_char(CH.START_TIME, 'DY') as F2,
		SUBSTR(AG.LASTNAME, 1,1) || '.' || AG.FIRSTNAME as F3,
		US.FIRSTNAME as F4,
		US.PHONENUMBER as F5,


		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = SERVICE_TYPE1 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F6_1,
		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = DETAILED_SERVICE_TYPE1 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F7_1,

		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = SERVICE_TYPE2 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F6_2,
		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = DETAILED_SERVICE_TYPE2 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F7_2,

		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = SERVICE_TYPE3 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F6_3,
		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = DETAILED_SERVICE_TYPE3 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F7_3,

		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = SERVICE_TYPE4 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F6_4,
		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = DETAILED_SERVICE_TYPE4 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F7_4,

		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = SERVICE_TYPE5 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F6_5,
		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = DETAILED_SERVICE_TYPE5 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F7_5,

		CALL_COMMENT as F8,
		(SELECT UNIT_NAME FROM MST_UNIT MU WHERE MU.UNIT_ID = CHS.UNIT_ID) as F9,
		(SELECT CALL_SORT_NAME FROM MST_CALL_SORT MCS WHERE MCS.CALL_SORT_ID = CHS.CALL_SORT_ID) as F10


	from CALL_HISTORY_SERVICE CHS

	LEFT JOIN CALL_HISTORY CH ON CH.CALL_HISTORY_ID = CHS.CALL_HISTORY_ID
	LEFT JOIN MST_AGENT AG ON AG.AGENT_ID = CH.AGENT_ID
 	LEFT JOIN MST_USERS US ON US.PHONENUMBER = CH.PHONENUMBER

	where CALL_REQ_TYPE = 3 AND (:DATE_FROM IS NULL OR :DATE_FROM <= to_char(CH.START_TIME, 'YYYY-MM-DD')) AND (:DATE_TO IS NULL OR :DATE_TO >= to_char(CH.START_TIME, 'YYYY-MM-DD')) AND (:AGENT_ID IS NULL OR :AGENT_ID = CH.AGENT_ID)
END
----------------------------InfoReqReport-----------------------------------------------------------------------------------------
BEGIN(Info)
		select
		to_char(CH.START_TIME, 'YYYY-MM-DD') as F1,
		to_char(CH.START_TIME, 'DY') as F2,
		SUBSTR(AG.LASTNAME, 1,1) || '.' || AG.FIRSTNAME as F3,
		US.FIRSTNAME as F4,
		US.PHONENUMBER as F5,


		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = SERVICE_TYPE1 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F6_1,
		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = DETAILED_SERVICE_TYPE1 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F7_1,

		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = SERVICE_TYPE2 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F6_2,
		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = DETAILED_SERVICE_TYPE2 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F7_2,

		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = SERVICE_TYPE3 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F6_3,
		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = DETAILED_SERVICE_TYPE3 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F7_3,

		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = SERVICE_TYPE4 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F6_4,
		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = DETAILED_SERVICE_TYPE4 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F7_4,

		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = SERVICE_TYPE5 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F6_5,
		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = DETAILED_SERVICE_TYPE5 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F7_5,

		CALL_COMMENT as F8

	from CALL_HISTORY_SERVICE CHS

	LEFT JOIN CALL_HISTORY CH ON CH.CALL_HISTORY_ID = CHS.CALL_HISTORY_ID
	LEFT JOIN MST_AGENT AG ON AG.AGENT_ID = CH.AGENT_ID
 	 LEFT JOIN MST_USERS US ON US.PHONENUMBER = CH.PHONENUMBER

	where CALL_REQ_TYPE = 2 AND (:DATE_FROM IS NULL OR :DATE_FROM <= to_char(CH.START_TIME, 'YYYY-MM-DD')) AND (:DATE_TO IS NULL OR :DATE_TO >= to_char(CH.START_TIME, 'YYYY-MM-DD')) AND (:AGENT_ID IS NULL OR :AGENT_ID = CH.AGENT_ID)
END

----------------------------ReferenceReport-----------------------------------------------------------------------------------------
BEGIN(Reference)
		select
		to_char(CH.START_TIME, 'YYYY-MM-DD') as F1,
		to_char(CH.START_TIME, 'DY') as F2,
		SUBSTR(AG.LASTNAME, 1,1) || '.' || AG.FIRSTNAME as F3,
		US.FIRSTNAME as F4,
		US.PHONENUMBER as F5,


		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = SERVICE_TYPE1 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F6_1,
		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = DETAILED_SERVICE_TYPE1 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F7_1,

		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = SERVICE_TYPE2 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F6_2,
		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = DETAILED_SERVICE_TYPE2 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F7_2,

		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = SERVICE_TYPE3 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F6_3,
		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = DETAILED_SERVICE_TYPE3 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F7_3,

		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = SERVICE_TYPE4 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F6_4,
		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = DETAILED_SERVICE_TYPE4 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F7_4,

		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = SERVICE_TYPE5 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F6_5,
		(SELECT SERVICE_NAME FROM MST_SERVICE WHERE SERVICE_ID = DETAILED_SERVICE_TYPE5 AND CHS.CALL_REQ_TYPE = CALL_REQ_TYPE_ID) as F7_5,

		CALL_COMMENT as F8

	from CALL_HISTORY_SERVICE CHS

	LEFT JOIN CALL_HISTORY CH ON CH.CALL_HISTORY_ID = CHS.CALL_HISTORY_ID
	LEFT JOIN MST_AGENT AG ON AG.AGENT_ID = CH.AGENT_ID
 	LEFT JOIN MST_USERS US ON US.PHONENUMBER = CH.PHONENUMBER

	where CALL_REQ_TYPE = 1 AND (:DATE_FROM IS NULL OR :DATE_FROM <= to_char(CH.START_TIME, 'YYYY-MM-DD')) AND (:DATE_TO IS NULL OR :DATE_TO >= to_char(CH.START_TIME, 'YYYY-MM-DD')) AND (:AGENT_ID IS NULL OR :AGENT_ID = CH.AGENT_ID)
END
----------------------------TransferReport-----------------------------------------------------------------------------------------
BEGIN(TransferReport)
		select
		to_char(CH.START_TIME, 'YYYY-MM-DD') as F1,
		to_char(CH.START_TIME, 'DY') as F2,
		SUBSTR(AG.LASTNAME, 1,1) || '.' || AG.FIRSTNAME as F3,
		US.FIRSTNAME as F4,
		US.PHONENUMBER as F5,
    	CHS.TRANSFER_PHONENUMBER as F6,
    	(SELECT UNIT_NAME FROM MST_UNIT MU WHERE MU.UNIT_ID = CHS.UNIT_ID) as F7,
		CALL_COMMENT as F8

		from CALL_HISTORY_SERVICE CHS

		LEFT JOIN CALL_HISTORY CH ON CH.CALL_HISTORY_ID = CHS.CALL_HISTORY_ID
		LEFT JOIN MST_AGENT AG ON AG.AGENT_ID = CH.AGENT_ID
 		LEFT JOIN MST_USERS US ON US.PHONENUMBER = CH.PHONENUMBER

		where CALL_REQ_TYPE = 5 AND (:DATE_FROM IS NULL OR :DATE_FROM <= to_char(CH.START_TIME, 'YYYY-MM-DD')) AND (:DATE_TO IS NULL OR :DATE_TO >= to_char(CH.START_TIME, 'YYYY-MM-DD')) AND (:AGENT_ID IS NULL OR :AGENT_ID = CH.AGENT_ID)
END
----------------------------OthersReport-------------------------------------------------------------------------------------------
BEGIN(OthersReport)
		select
		to_char(CH.START_TIME, 'YYYY-MM-DD') as F1,
		to_char(CH.START_TIME, 'DY') as F2,
		SUBSTR(AG.LASTNAME, 1,1) || '.' || AG.FIRSTNAME as F3,
		US.FIRSTNAME as F4,
		US.PHONENUMBER as F5,
    	(SELECT UNIT_NAME FROM MST_UNIT MU WHERE MU.UNIT_ID = CHS.UNIT_ID) as F6,
		CALL_COMMENT as F7

		from CALL_HISTORY_SERVICE CHS

		LEFT JOIN CALL_HISTORY CH ON CH.CALL_HISTORY_ID = CHS.CALL_HISTORY_ID
		LEFT JOIN MST_AGENT AG ON AG.AGENT_ID = CH.AGENT_ID
 		LEFT JOIN MST_USERS US ON US.PHONENUMBER = CH.PHONENUMBER

		where CALL_REQ_TYPE = 6 AND (:DATE_FROM IS NULL OR :DATE_FROM <= to_char(CH.START_TIME, 'YYYY-MM-DD')) AND (:DATE_TO IS NULL OR :DATE_TO >= to_char(CH.START_TIME, 'YYYY-MM-DD')) AND (:AGENT_ID IS NULL OR :AGENT_ID = CH.AGENT_ID)
END
----------------------------UnsolvedComplaintReport-------------------------------------------------------------------------------------------
BEGIN(SolvedComplaintReport)
		select
		to_char(C.INSERT_DATE, 'YYYY-MM-DD') as F1,
		to_char(C.INSERT_DATE, 'DY') as F2,
		SUBSTR(AG.LASTNAME, 1,1) || '.' || AG.FIRSTNAME as F3,
		C.CALLER_NAME as F4,
   	 	C.PHONE_NUMBER_ONE as F5,
    	C.CALLER_EMAIL as F6,
    	(SELECT SERVICE_NAME FROM MST_SERVICE S1 WHERE S1.SERVICE_ID = C.SERVICE_ID)as F7,
    	(SELECT SERVICE_NAME FROM MST_SERVICE S2 WHERE S2.SERVICE_ID = C.DETAILED_SERVICE_ID)as F8,
    	(SELECT CALL_RATE_NAME FROM MST_CALL_RATE CRA WHERE CRA.CALL_RATE_ID = C.CALL_RATE_ID)as F9,
    	(SELECT UNIT_NAME FROM MST_UNIT MU WHERE MU.UNIT_ID = C.UNIT_ID) as F10,
    	(SELECT CALL_RESULT_NAME FROM MST_CALL_RESULT CRE WHERE CRE.CALL_RESULT_ID = C.CALL_RESULT_ID)as F11,
    	C.SOLVED_DATE as F12,
		C.SOLVED_COMMENT as F13
		from COMPLAINT C
		LEFT JOIN MST_AGENT AG ON AG.AGENT_ID = C.AGENT_ID
 		LEFT JOIN MST_USERS US ON US.PHONENUMBER = C.PHONE_NUMBER_ONE
 		
    	WHERE SOLVED_STATUS='1' AND (:DATE_FROM IS NULL OR :DATE_FROM <= to_char(C.INSERT_DATE, 'YYYY-MM-DD')) AND (:DATE_TO IS NULL OR :DATE_TO >= to_char(C.INSERT_DATE, 'YYYY-MM-DD')) AND (:AGENT_ID IS NULL OR :AGENT_ID = C.AGENT_ID)
END
----------------------------UnsolvedComplaintReport-------------------------------------------------------------------------------------------
BEGIN(UnsolvedComplaintReport)
		select
		to_char(C.INSERT_DATE, 'YYYY-MM-DD') as F1,
		to_char(C.INSERT_DATE, 'DY') as F2,
		SUBSTR(AG.LASTNAME, 1,1) || '.' || AG.FIRSTNAME as F3,
		C.CALLER_NAME as F4,
   	 	C.PHONE_NUMBER_ONE as F5,
    	C.CALLER_EMAIL as F6,
    	(SELECT SERVICE_NAME FROM MST_SERVICE S1 WHERE S1.SERVICE_ID = C.SERVICE_ID)as F7,
    	(SELECT SERVICE_NAME FROM MST_SERVICE S2 WHERE S2.SERVICE_ID = C.DETAILED_SERVICE_ID)as F8,
    	(SELECT CALL_RATE_NAME FROM MST_CALL_RATE CRA WHERE CRA.CALL_RATE_ID = C.CALL_RATE_ID)as F9,
    	(SELECT UNIT_NAME FROM MST_UNIT MU WHERE MU.UNIT_ID = C.UNIT_ID) as F10,
    	(SELECT CALL_RESULT_NAME FROM MST_CALL_RESULT CRE WHERE CRE.CALL_RESULT_ID = C.CALL_RESULT_ID)as F11
		from COMPLAINT C
		LEFT JOIN MST_AGENT AG ON AG.AGENT_ID = C.AGENT_ID
 		LEFT JOIN MST_USERS US ON US.PHONENUMBER = C.PHONE_NUMBER_ONE
 		
    	WHERE SOLVED_STATUS='0' AND (:DATE_FROM IS NULL OR :DATE_FROM <= to_char(C.INSERT_DATE, 'YYYY-MM-DD')) AND (:DATE_TO IS NULL OR :DATE_TO >= to_char(C.INSERT_DATE, 'YYYY-MM-DD')) AND (:AGENT_ID IS NULL OR :AGENT_ID = C.AGENT_ID)
END
----------------------------CallRate-------------------------------------------------------------------------------------------
BEGIN(CallRate)
	select
		CASE when	(SELECT CALL_RATE_NAME FROM MST_CALL_RATE CR WHERE CR.CALL_RATE_ID = CHS.CALL_RATE_ID) is null then :SYSTEMRATE else (SELECT CALL_RATE_NAME FROM MST_CALL_RATE CR WHERE CR.CALL_RATE_ID = CHS.CALL_RATE_ID) END as G1,
		to_char(CH.START_TIME, 'YYYY-MM-DD') as F1,
		to_char(CH.START_TIME, 'DY') as F2,
		SUBSTR(AG.LASTNAME, 1,1) || '.' || AG.FIRSTNAME as F3,
		US.FIRSTNAME as F4,
		CH.PHONENUMBER as F5,
		(SELECT CALL_REQ_TYPE_NAME FROM MST_CALL_REQ_TYPE CRT WHERE CRT.CALL_REQ_TYPE_ID = CHS.CALL_REQ_TYPE) as F6

		from CALL_HISTORY_SERVICE CHS

		LEFT JOIN CALL_HISTORY CH ON CH.CALL_HISTORY_ID = CHS.CALL_HISTORY_ID
		LEFT JOIN MST_AGENT AG ON AG.AGENT_ID = CH.AGENT_ID
 		LEFT JOIN MST_USERS US ON US.PHONENUMBER = CH.PHONENUMBER
		WHERE (:DATE_FROM IS NULL OR :DATE_FROM <= to_char(CH.START_TIME, 'YYYY-MM-DD')) AND (:DATE_TO IS NULL OR :DATE_TO >= to_char(CH.START_TIME, 'YYYY-MM-DD')) AND (:AGENT_ID IS NULL OR :AGENT_ID = CH.AGENT_ID)
		ORDER BY
			G1
			  ASC
END

----------------------------CallResult-------------------------------------------------------------------------------------------
BEGIN(CallResult)
	select
		(SELECT CALL_RESULT_NAME FROM MST_CALL_RESULT CR WHERE CR.CALL_RESULT_ID = CHS.CALL_RESULT_ID) as G1,
		to_char(CH.START_TIME, 'YYYY-MM-DD') as F1,
		to_char(CH.START_TIME, 'DY') as F2,
		SUBSTR(AG.LASTNAME, 1,1) || '.' || AG.FIRSTNAME as F3,
		US.FIRSTNAME as F4,
		CH.PHONENUMBER as F5,
		(SELECT CALL_REQ_TYPE_NAME FROM MST_CALL_REQ_TYPE CRT WHERE CRT.CALL_REQ_TYPE_ID = CHS.CALL_REQ_TYPE) as F6

		from CALL_HISTORY_SERVICE CHS

		LEFT JOIN CALL_HISTORY CH ON CH.CALL_HISTORY_ID = CHS.CALL_HISTORY_ID
		LEFT JOIN MST_AGENT AG ON AG.AGENT_ID = CH.AGENT_ID
 		LEFT JOIN MST_USERS US ON US.PHONENUMBER = CH.PHONENUMBER
		WHERE (:DATE_FROM IS NULL OR :DATE_FROM <= to_char(CH.START_TIME, 'YYYY-MM-DD')) AND (:DATE_TO IS NULL OR :DATE_TO >= to_char(CH.START_TIME, 'YYYY-MM-DD')) AND (:AGENT_ID IS NULL OR :AGENT_ID = CH.AGENT_ID)
		ORDER BY
			G1
			  ASC
END
-----------------------------Calltype-------------------------------------------------------------
BEGIN(Calltype)
	SELECT COUNT(*) as F1
		FROM CALL_HISTORY_SERVICE CHS
		LEFT JOIN CALL_HISTORY CH ON CH.CALL_HISTORY_ID = CHS.CALL_HISTORY_ID

		WHERE CALL_REQ_TYPE <> '0' AND (:DATE_FROM IS NULL OR :DATE_FROM <= to_char(CH.START_TIME, 'YYYY-MM-DD')) AND (:DATE_TO IS NULL OR :DATE_TO >= to_char(CH.START_TIME, 'YYYY-MM-DD')) AND (:AGENT_ID IS NULL OR :AGENT_ID = CH.AGENT_ID)
	GROUP BY CALL_REQ_TYPE
	ORDER BY CALL_REQ_TYPE
END
-----------------------------Callsum------------------------------------------------------------
BEGIN(Callsum)
	 SELECT COUNT(*) AS F1
 	 FROM CALL_HISTORY CH
  	WHERE CALLTYPE=0
    AND (:DATE_FROM IS NULL OR :DATE_FROM <= to_char(CH.START_TIME, 'YYYY-MM-DD')) 
    AND (:DATE_TO IS NULL OR :DATE_TO >= to_char(CH.START_TIME, 'YYYY-MM-DD'))
    AND (:AGENT_ID IS NULL OR :AGENT_ID = CH.AGENT_ID)
END
----------------------------Byhour----------------------------------------------------------------
BEGIN(HandledCalls)
	SELECT  COUNT(*) - 1 as F1 FROM (

  		SELECT TO_TIMESTAMP('00', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('01', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('02', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('03', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('04', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('05', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('06', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('07', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('08', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('09', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('10', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('11', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('12', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('13', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('14', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('15', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('16', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('17', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('18', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('19', 'HH24') as START_TIME FROM dual
 		 	union all SELECT TO_TIMESTAMP('20', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('21', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('22', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('23', 'HH24') as START_TIME FROM dual
  			union all SELECT START_TIME FROM CALL_HISTORY CH WHERE (:DATE_FROM IS NULL OR :DATE_FROM <= to_char(CH.START_TIME, 'YYYY-MM-DD')) AND (:DATE_TO IS NULL OR :DATE_TO >= to_char(CH.START_TIME, 'YYYY-MM-DD')) AND (:AGENT_ID IS NULL OR :AGENT_ID = CH.AGENT_ID) )

	GROUP BY  TO_CHAR(START_TIME, 'HH24')
	ORDER BY  TO_CHAR(START_TIME, 'HH24')
END

BEGIN(Abandonedcalls)
SELECT COUNT(*)-1 as F1 FROM (

        SELECT TO_TIMESTAMP('00', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('01', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('02', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('03', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('04', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('05', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('06', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('07', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('08', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('09', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('10', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('11', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('12', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('13', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('14', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('15', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('16', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('17', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('18', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('19', 'HH24') as START_TIME FROM dual
        	union all SELECT TO_TIMESTAMP('20', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('21', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('22', 'HH24') as START_TIME FROM dual
  			union all SELECT TO_TIMESTAMP('23', 'HH24') as START_TIME FROM dual
  			union all SELECT START_TIME FROM CALL_HISTORY CH 
        WHERE CALLTYPE='3' AND (:DATE_FROM IS NULL OR :DATE_FROM <= to_char(CH.START_TIME, 'YYYY-MM-DD')) AND (:DATE_TO IS NULL OR :DATE_TO >= to_char(CH.START_TIME, 'YYYY-MM-DD')) AND (:AGENT_ID IS NULL OR :AGENT_ID = CH.AGENT_ID))

	GROUP BY  TO_CHAR(START_TIME, 'HH24')
	ORDER BY  TO_CHAR(START_TIME, 'HH24')
END
-----------------------------------------Byday--------------------------------------------------------
BEGIN(byDay)
	SELECT
		substr((SELECT lastname FROM mst_agent ma WHERE ma.agent_id = ch.agent_id),1,1)
		||'.'||(SELECT firstname FROM mst_agent ma WHERE ma.agent_id = ch.agent_id) as F1,
		sectotime(sum(timetonumber(ch.finished_time, ch.start_time))) as sumcallduration,
		count(*) as F3,
		(SELECT COUNT(*) FROM MST_AGENT_LOG MAL WHERE MAL.AGENT_ID = CH.AGENT_ID AND STATUS='5') AS abandonedcalls
	from call_history ch

	where ch.finished_time is not null and ch.start_time is not null AND (:DATE_FROM IS NULL OR :DATE_FROM <= to_char(CH.START_TIME, 'YYYY-MM-DD')) AND (:DATE_TO IS NULL OR :DATE_TO >= to_char(CH.START_TIME, 'YYYY-MM-DD')) AND (:AGENT_ID IS NULL OR :AGENT_ID = CH.AGENT_ID) 

  			group by agent_id
  			order by agent_id
END
---------------------------------------Byagent--------------------------------------------------------

BEGIN(INBOUND_REPORT)
   SELECT F1, F2, F3, F4 + F6 as F4, F5, F6, (ROUND(F5 / (F4 + F6),6))*100 as F7, F8, F9, F10 FROM
  (
		select
			to_char(START_TIME, 'DY') as F1,
			to_char(START_TIME, 'YYYY-MM-DD') as F2,
			COUNT(DISTINCT CH.AGENT_ID) as F3,
			COUNT(*) as F4,
			COUNT(*) as F5,
      T2.COUNTER AS F6,
      
			TO_CHAR(TRUNC (SYSDATE) + NUMTODSINTERVAL(SUM(TIMESTAMP_DIFF_IN_SECONDS(FINISHED_TIME, START_TIME)), 'second'), 'hh24:mi:ss') as F8,
			TO_CHAR(TRUNC (SYSDATE) + NUMTODSINTERVAL(AVG(TIMESTAMP_DIFF_IN_SECONDS(FINISHED_TIME, START_TIME)), 'second'), 'hh24:mi:ss') as F9,
			TO_CHAR(TRUNC (SYSDATE) + NUMTODSINTERVAL(MAX(TIMESTAMP_DIFF_IN_SECONDS(FINISHED_TIME, START_TIME)), 'second'), 'hh24:mi:ss') as F10

		from CALL_HISTORY CH  ,
   (
    SELECT DISTINCT 
    CASE WHEN T1.COUNTER IS NULL
    THEN 0
    ELSE T1.COUNTER
    END AS COUNTER ,to_char(T2.START_TIME, 'YYYY-MM-DD') AS TIMESSS   FROM 
	(SELECT  COUNT(*) AS COUNTER ,to_char(CHH.START_TIME, 'YYYY-MM-DD')  AS TIMESSS
	FROM CALL_HISTORY CHH 
	WHERE CHH.CALLTYPE = 3 GROUP BY to_char(CHH.START_TIME, 'YYYY-MM-DD') ) T1
	RIGHT JOIN 
	CALL_HISTORY T2 ON T1.TIMESSS = to_char(T2.START_TIME, 'YYYY-MM-DD')
   )
    T2
		WHERE CALLTYPE = 0 
    AND to_char(CH.START_TIME, 'YYYY-MM-DD') = T2.TIMESSS
    AND FINISHED_TIME IS NOT NULL
	AND (:DATE_FROM IS NULL OR :DATE_FROM <= to_char(CH.START_TIME, 'YYYY-MM-DD')) AND (:DATE_TO IS NULL OR :DATE_TO >= to_char(CH.START_TIME, 'YYYY-MM-DD')) AND (:AGENT_ID IS NULL OR :AGENT_ID = CH.AGENT_ID)
		group by 	to_char(START_TIME, 'DY'),  to_char(START_TIME, 'YYYY-MM-DD'), T2.COUNTER
		order by to_char(START_TIME, 'YYYY-MM-DD') 
	)
END

BEGIN(OUTBOUND_REPORT)
	SELECT F1, F2, F3, F4, F5, F6, F7  FROM (
		select
			to_char(START_TIME, 'DY') as F1,
			to_char(START_TIME, 'YYYY-MM-DD') as F2,
			COUNT(DISTINCT CH.AGENT_ID) as F3,
			COUNT(*) as F4,
			TO_CHAR(TRUNC (SYSDATE) + NUMTODSINTERVAL(SUM(TIMESTAMP_DIFF_IN_SECONDS(FINISHED_TIME, START_TIME)), 'second'), 'hh24:mi:ss') as F5,
			TO_CHAR(TRUNC (SYSDATE) + NUMTODSINTERVAL(AVG(TIMESTAMP_DIFF_IN_SECONDS(FINISHED_TIME, START_TIME)), 'second'), 'hh24:mi:ss') as F6,
			TO_CHAR(TRUNC (SYSDATE) + NUMTODSINTERVAL(MAX(TIMESTAMP_DIFF_IN_SECONDS(FINISHED_TIME, START_TIME)), 'second'), 'hh24:mi:ss') as F7
			
		from CALL_HISTORY CH

		WHERE CALLTYPE = 1
		AND FINISHED_TIME IS NOT NULL 
		AND (:DATE_FROM IS NULL OR :DATE_FROM <= to_char(CH.START_TIME, 'YYYY-MM-DD')) AND (:DATE_TO IS NULL OR :DATE_TO >= to_char(CH.START_TIME, 'YYYY-MM-DD')) AND (:AGENT_ID IS NULL OR :AGENT_ID = CH.AGENT_ID)


		group by to_char(START_TIME, 'DY'),  to_char(START_TIME, 'YYYY-MM-DD')
		order by to_char(START_TIME, 'YYYY-MM-DD')
	)
END

BEGIN(BY_AGENT)
	select G1, F1, F2, F4 AS F3, F5 AS F4, F6 AS F5, (F7+F8) AS F6, F7 as F7,  
	ROUND(F9,6)*100 AS F8,
  F10 AS F9, 
	ROUND(CALC_RATIO(F10, F6),6)*100 as F10, 
  F12 AS F11, 
	ROUND(CALC_RATIO(F12, F6),6)*100 as F12, 
  F14 AS F13,
	ROUND(CALC_RATIO(F14, F6),6)*100 as F14, 
  F16 AS F15, 
  F17 AS F16, 
  F18 AS F17, 
  F19 AS F18, 
  F20 AS F19, 
  F21 AS F20
from VIEW_REPORT_BY_AGENT VRA
	WHERE (:DATE_FROM IS NULL OR :DATE_FROM <= VRA.F1) AND (:DATE_TO IS NULL OR :DATE_TO >= VRA.F1) AND (:AGENT_ID IS NULL OR :AGENT_ID = VRA.AGENT_ID)
END
--------------------------------------------------byday--------------------------------------------------
BEGIN(BYDAYSUM)
	SELECT
		to_char(START_TIME,'YYYY-MM-DD') as F1,
		(SELECT COUNT(*) FROM CALL_HISTORY CHH WHERE TO_CHAR(CHH.START_TIME, 'YYYY-MM-DD') = TO_CHAR(CH.START_TIME, 'YYYY-MM-DD') and CALLTYPE ='0' AND CHH.FINISHED_TIME IS NOT NULL) + 
    	(SELECT COUNT(*) FROM CALL_HISTORY CHH WHERE TO_CHAR(CHH.START_TIME, 'YYYY-MM-DD') = TO_CHAR(CH.START_TIME, 'YYYY-MM-DD') and CALLTYPE ='3') as F2,
		(SELECT COUNT(*) FROM CALL_HISTORY CHH WHERE TO_CHAR(CHH.START_TIME, 'YYYY-MM-DD') = TO_CHAR(CH.START_TIME, 'YYYY-MM-DD') and CALLTYPE ='0' AND CHH.FINISHED_TIME IS NOT NULL) AS F3,
		(SELECT COUNT(*) FROM CALL_HISTORY CHH WHERE TO_CHAR(CHH.START_TIME, 'YYYY-MM-DD') = TO_CHAR(CH.START_TIME, 'YYYY-MM-DD') and CALLTYPE ='3') AS F4,
		(select sectotime(sum(timetonumber(to_timestamp(f5,'hh24:mi:ss'), to_timestamp(f4,'hh24:mi:ss')))) from view_report_by_agent where f1 = to_char(ch.start_time,'YYYY-MM-DD')) as F5,
		'' as F6,
 		'' as F7,
		sectotime(sum(timetonumber(ch.finished_time, ch.start_time))) AS F8
	FROM CALL_HISTORY CH
		where ch.finished_time is not null and ch.start_time is not null 
		AND (:DATE_FROM = to_char(CH.START_TIME, 'YYYY-MM-DD')) AND (:AGENT_ID IS NULL OR :AGENT_ID = CH.AGENT_ID)
		group by to_char(START_TIME, 'DY'),  to_char(START_TIME, 'YYYY-MM-DD')
		ORDER by to_char(START_TIME, 'YYYY-MM-DD')
END

BEGIN(BYDAYNAMES)
select f1, f2, f3, f4, f5, 
CASE WHEN f5 != 0 THEN round(F4/F5,6)*100 ELSE 0 end as f6, f7, f8, f9
from (
		SELECT
		to_char(START_TIME,'YYYY-MM-DD') as F1,
		(SELECT FIRSTNAME FROM MST_AGENT MA WHERE CH.AGENT_ID = MA.AGENT_ID) as F2,
		(select f6 from view_report_by_agent where f1 = to_char(ch.start_time,'YYYY-MM-DD') and ch.agent_id = agent_id) as F3,
		(select f7 from view_report_by_agent where f1 = to_char(ch.start_time,'YYYY-MM-DD') and ch.agent_id = agent_id) as F4,
		(select f7 + f8 from view_report_by_agent where f1 = to_char(ch.start_time,'YYYY-MM-DD') and ch.agent_id = agent_id) as F5,
		'0' as F6,
		(select f14 from view_report_by_agent where f1 = to_char(ch.start_time,'YYYY-MM-DD') and ch.agent_id = agent_id) as F7,
		' ' as F8,
		(select f12 from view_report_by_agent where f1 = to_char(ch.start_time,'YYYY-MM-DD') and ch.agent_id = agent_id) as F9
	FROM CALL_HISTORY CH

	where ch.finished_time is not null and ch.start_time is not null 
	AND (:DATE_FROM = to_char(CH.START_TIME, 'YYYY-MM-DD')) AND (:AGENT_ID IS NULL OR :AGENT_ID = CH.AGENT_ID)
	group by CH.agent_id, to_char(START_TIME,'YYYY-MM-DD')
  )
END